language: node_js

sudo: false

matrix:
  fast_finish: true

node_js:
  - "8"

branches:
  only:
  - master

git:
  depth: 1

cache:
  directories:
    - "node_modules"

script:
  - npm run compile
  - npm run lint
  - npm run compile-tests
  - npm run test
