# https://circleci.com/docs/2.0/configuration-reference

version: 2.1


aliases:
  - &restore-node-modules-cache
      name: Restore node_modules cache
      keys:
        - &cache-key v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".dev-deps/package.json" }}

  - &save-node-modules-cache
      name: Save node_modules cache
      paths:
        - node_modules
        - .dev-deps/node_modules
      key: *cache-key

  - &default-filters
      tags:
        ignore:
          - /.*/


executors:
  node-latest-executor:
    docker:
      - image: circleci/node:8


commands:
  checkout-with-deps:
    description: "Checkout the code with restore npm dependencies"
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache

  compile-and-test:
    description: "Checkout the code with restore npm dependencies"
    steps:
      - run:
          name: "Setup Environment Variables"
          command: |
            echo 'export TESTS_REPORT_FILE="test-results/results.xml"' >> $BASH_ENV
      - run: npm run compile
      - run: npm run test
      - store_test_results:
          path: test-results/
      - run: npm run bundle-dts


jobs:
  install_deps:
    executor: node-latest-executor
    steps:
      - checkout-with-deps
      - run: npm install
      - save_cache: *save-node-modules-cache

  lint:
    executor: node-latest-executor
    steps:
      - checkout-with-deps
      - run: npm run lint

  ts_min:
    executor: node-latest-executor
    steps:
      - checkout-with-deps
      - run: npm install typescript@2.6.1
      - run: npm run compile

  ts_current:
    executor: node-latest-executor
    steps:
      - checkout-with-deps
      - compile-and-test

  ts_next:
    executor: node-latest-executor
    steps:
      - checkout-with-deps
      - run: npm install typescript@next
      - compile-and-test


workflows:
  version: 2

  main-workflow:
    jobs:
      - install_deps:
          filters: *default-filters

      - lint:
          filters: *default-filters
          requires:
            - install_deps
      - ts_min:
          filters: *default-filters
          requires:
            - install_deps
      - ts_current:
          filters: *default-filters
          requires:
            - install_deps
      - ts_next:
          filters: *default-filters
          requires:
            - install_deps
